"""Add portfolio adjustment

Revision ID: 28d588293334
Revises: 577c289bf3fd
Create Date: 2020-12-19 00:45:06.199778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28d588293334'
down_revision = '577c289bf3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_adjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('DEPOSIT', 'WITHDRAW', 'INTERNAL_TRANSFER', 'BROKER_INTEREST_PAID', 'ACCOUNT_TRANSFER', 'OTHER_FEES', 'INTEREST_YOU_PAID', name='adjustmenttype'), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('portfolio_id', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_adjustment_id'), 'portfolio_adjustment', ['id'], unique=False)
    op.create_index(op.f('ix_portfolio_adjustment_type'), 'portfolio_adjustment', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_portfolio_adjustment_type'), table_name='portfolio_adjustment')
    op.drop_index(op.f('ix_portfolio_adjustment_id'), table_name='portfolio_adjustment')
    op.drop_table('portfolio_adjustment')
    # ### end Alembic commands ###
