"""Add more trade properties

Revision ID: 2ed8bea5d917
Revises: 28d588293334
Create Date: 2020-12-22 05:14:47.142994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ed8bea5d917'
down_revision = '28d588293334'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('execution', sa.Column('initial_position', sa.Boolean(), nullable=True, default=False))
    op.add_column('trade', sa.Column('initial_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('initial_shares', sa.Integer(), nullable=True))
    op.add_column('trade', sa.Column('initial_stop', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('return_rate', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trade', 'return_rate')
    op.drop_column('trade', 'initial_stop')
    op.drop_column('trade', 'initial_shares')
    op.drop_column('trade', 'initial_price')
    op.drop_column('execution', 'initial_position')
    # ### end Alembic commands ###
