"""trade and execution db schema change

Revision ID: f4f2a492f28e
Revises: 64a2c0267548
Create Date: 2020-11-29 19:53:26.823415

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f4f2a492f28e'
down_revision = '64a2c0267548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # fix bug not able to create enum
    trade_status = postgresql.ENUM('OPEN', 'WIN', 'LOSS', 'BE', name='trade_status')
    trade_status.create(op.get_bind())    
    op.add_column('execution', sa.Column('reason', sa.String(), nullable=True))
    op.add_column('execution', sa.Column('setup', sa.String(), nullable=True))
    op.add_column('trade', sa.Column('entry_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('exit_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('net_profit', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('trade', sa.Column('open_shares', sa.Integer(), nullable=True))
    op.add_column('trade', sa.Column('rmultiple', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('setup', sa.String(), nullable=True))
    op.add_column('trade', sa.Column('status', sa.Enum('OPEN', 'WIN', 'LOSS', 'BE', name='trade_status'), server_default="OPEN", nullable=False))
    op.add_column('trade', sa.Column('stop_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('target_price', sa.Float(), nullable=True))
    op.add_column('trade', sa.Column('total_shares', sa.Integer(), nullable=True))
    op.drop_column('trade', 'current_position')
    op.drop_column('trade', 'current_risk')
    op.drop_column('trade', 'initial_risk')
    op.drop_column('trade', 'initial_position')
    op.drop_column('trade', 'profit_lost')
    op.drop_column('trade', 'risk_ratio')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trade', sa.Column('risk_ratio', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('profit_lost', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('initial_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('initial_risk', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('current_risk', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('trade', sa.Column('current_position', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('trade', 'total_shares')
    op.drop_column('trade', 'target_price')
    op.drop_column('trade', 'stop_price')
    op.drop_column('trade', 'status')
    op.drop_column('trade', 'setup')
    op.drop_column('trade', 'rmultiple')
    op.drop_column('trade', 'open_shares')
    op.drop_column('trade', 'notes')
    op.drop_column('trade', 'net_profit')
    op.drop_column('trade', 'exit_price')
    op.drop_column('trade', 'entry_price')
    op.drop_column('execution', 'setup')
    op.drop_column('execution', 'reason')

    # fix bug not able to create enum
    trade_status = postgresql.ENUM('OPEN', 'WIN', 'LOSS', 'BE', name='trade_status')
    trade_status.drop(op.get_bind())
    # ### end Alembic commands ###
